"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

from datetime import timedelta

import os


import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q$mvcx_r7)3vgpmiliudisugniy-@8cogbj-mfz-%6l(p4n+ef'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    "livkit.onrender.com",
    "localhost",
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',

    'accounts',
    'payments',
    'official_site',
    'chat',
    'channels',
    
    'django_celery_beat',

    'streaming',
    
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}



DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DATABASE_URL")
    )
}




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


STATIC_URL = "/assets/"

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "assets"),
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'accounts.User'




FRONTEND_SUCCESS_URL = "https://livkit.onrender.com/dashboard"
FRONTEND_CANCEL_URL = "https://livkit.onrender.com/payment-cancel"


AUTHENTICATION_BACKENDS = [
    "accounts.backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "accounts.auth.CookieJWTAuthentication",
    ),
}




SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("Bearer",),

    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),

    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,

    "UPDATE_LAST_LOGIN": True,

}


GOOGLE_PLAY_SERVICE_ACCOUNT = BASE_DIR / "payments" / "google_service.json"
GOOGLE_PACKAGE_NAME = "com.yourcompany.livkit"  # your Android package
GOOGLE_PRODUCT_ID = "lifetime_premium"          # match Flutter


ASGI_APPLICATION = "backend.asgi.application"


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [{
                "address": "rediss://default:ASoQAAIncDI0NmM4MjU3MDliZTA0ZjNkYjY4ODE3NWVlOWQ3OGU1MXAyMTA3Njg@gentle-yeti-10768.upstash.io:6379",
               
                "ssl_cert_reqs": None,
            }],
        },
    },
}







MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"



AGORA_APP_ID = "9d64feede1574163bbffbf85bb10f8e6"
AGORA_APP_CERTIFICATE = "f9367fb864d94ed3a0172b7a11c99fa0"

# Token expiry (seconds) — 1 hour is reasonable for live streaming
AGORA_TOKEN_TTL = 3600

CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

# =======================
# STREAMING MONETIZATION
# =======================
EARNINGS_CENTS_PER_VIEWER_MINUTE = 5  # $0.05 per viewer per minute




STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET")
STRIPE_PRICE_ID = os.environ.get("STRIPE_PRICE_ID")


# =======================
# LIVESTREAM MINUTES PAYMENT
# =======================
STRIPE_MINUTES_WEBHOOK_SECRET = os.environ.get("STRIPE_MINUTES_WEBHOOK_SECRET")

STRIPE_MINUTES_PRICE_ID =  os.environ.get("STRIPE_MINUTES_PRICE_ID") 

# How many seconds per purchase
SECONDS_PER_MINUTE_PACKAGE = 18000  # 300 minutes = 18,000 seconds


STREAMER_RATE_PER_VIEWER_HOUR = 0.208
STREAMER_RATE_PER_VIEWER_SECOND = 0.208 / 3600  # = 0.000057777...
